version: '3'
services:

  redis:
    image: "redis:alpine"
    restart: "unless-stopped"

  app:
    build: .
    volumes: 
      - "./stores.json:/tmp/stores.json"
      - "./flask_app:/flask_app"
    restart: "unless-stopped"
    depends_on: 
      - redis

  nginx:
    image: "nginx:1.19.0-alpine"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf   
    restart: "unless-stopped"
    depends_on: 
      - app
